[deploy]
bucket = 'cfn-artifacts.cruddur.daviu.com.es'
region = 'eu-central-1'
stack_name = 'CrdSyncRole'

[parameters]
GitHubOrg = 'xavierdaviu'
RepositoryName = 'aws-bootcamp-cruddur-2023'
OIDCProviderArn = ''