[deploy]
bucket = 'cfn-artifacts.cruddur.daviu.com.es'
region = 'eu-central-1'
stack_name = 'CruddurServiceBackendFlask'

[parameters]
EnvFrontendUrl = 'https://cruddur.daviu.com.es'
EnvBackendUrl = 'https://api.cruddur.daviu.com.es'
DDBMessageTable = 'CrdDdb-DynamoDBTable-G12N0ET4TBR0'