[deploy]
bucket = 'cfn-artifacts.cruddur.daviu.com.es'
region = 'eu-central-1'
stack_name = 'CruddurDb'

[parameters]
NetworkingStack = 'CruddurNetwork'
ClusterStack = 'CruddurCluster'
MasterUsername = 'cruddurroot'