[deploy]
bucket = 'cfn-artifacts.cruddur.daviu.com.es'
region = 'eu-central-1'
stack_name = 'CrdCicd'

[parameters]
ServiceStack = 'CrdSrvBackendFlask'
ClusterStack = 'CrdCluster'
GitHubBranch = 'prod'
GithubRepo = 'xavierdaviu/aws-bootcamp-cruddur-2023'
ArtifactBucketName = "codepipeline-artifacts.cruddur.daviu.com.es"
BuildSpec = 'backend-flask/buildspec.yml'